export const DoctorsData = [
  {
    image: "/assets/images/dr-green.png",
    doctor: "Dr. John Green",
    hospital: "CrossRoads Hospital",
    speciality: "Pediatrician",
    days: "Monday, Tuesday, Thursday",
    timings: "5:30PM - 8:00PM",
    color: "#000",
  },
  {
    image: "/assets/images/dr-cameron.png",
    doctor: "Dr. Leila Cameron",
    hospital: "Little River Hospital",
    speciality: "ENT",
    days: "Monday, Wednesday, Friday",
    timings: "6:00PM - 7:30PM",
    color: "#000",
  },
  {
    image: "/assets/images/dr-livingston.png",
    doctor: "Dr. David Livingston",
    hospital: "United Hospital",
    speciality: "ENT",
    days: "All Weekdays",
    timings: "8:30AM - 10:00AM",
    color: "#000",
  },
  {
    image: "/assets/images/dr-peter.png",
    doctor: "Dr. Evan Peter",
    hospital: "Hopevale Hospital",
    speciality: "Gastroenterologists",
    days: "Saturday, Sunday",
    timings: "7:00PM - 8:30PM",
    color: "#000",
  },
  {
    image: "/assets/images/dr-powell.png",
    doctor: "Dr. Jane Powell",
    hospital: "Morningside General Hospital",
    speciality: "General",
    days: "Tuesday, Thursday",
    timings: "7:30AM - 10:00AM",
    color: "#000",
  },
  {
    image: "/assets/images/dr-remirez.png",
    doctor: "Dr. Alex Ramirez",
    hospital: "CrossRoads Hospital",
    speciality: "Orthopedic",
    days: "Monday, Tuesday, Thursday",
    timings: "5:30PM - 8:00PM",
    color: "#000",
  },
  {
    image: "/assets/images/dr-lee.png",
    doctor: "Dr. Jasmine Lee",
    hospital: "United Hospital",
    speciality: "General",
    days: "Saturday, Sunday",
    timings: "8:30AM - 10:00AM",
  },
  {
    image: "/assets/images/dr-cruz.png",
    doctor: "Dr. Alyana Cruz",
    hospital: "Morningside General Hospital",
    speciality: "Pediatrician",
    days: "All Weekdays",
    timings: "7:00PM - 8:30PM",
    color: "#000",
  },
  {
    image: "/assets/images/dr-sharma.png",
    doctor: "Dr. Hardik Sharma",
    hospital: "Hopevale Hospital",
    speciality: "Orthopedic",
    days: "Tuesday, Thursday",
    timings: "7:30AM - 10:00AM",
    color: "#000",
  },
];
